version: "3"
services:
  mdbook:
    build: .
    container_name: mdbook-test
    volumes:
      - ./:/mdbook
    ports:
      - "3000:3000"
      - "3001:3001"
    command:
      - mdbook
      - serve
      - --hostname
      - "0.0.0.0"